/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/cs': RouteRecordInfo<
      '/about/cs',
      '/about/cs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/en': RouteRecordInfo<
      '/about/en',
      '/about/en',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/courses': RouteRecordInfo<
      '/courses',
      '/courses',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/': RouteRecordInfo<
      '/guide/',
      '/guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/cs': RouteRecordInfo<
      '/guide/cs',
      '/guide/cs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/en': RouteRecordInfo<
      '/guide/en',
      '/guide/en',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/[locale]/[slug]': RouteRecordInfo<
      '/legal/[locale]/[slug]',
      '/legal/:locale/:slug',
      { locale: ParamValue<true>, slug: ParamValue<true> },
      { locale: ParamValue<false>, slug: ParamValue<false> },
      | never
    >,
    '/legal/[slug]': RouteRecordInfo<
      '/legal/[slug]',
      '/legal/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/about/index.vue': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/about/cs.vue': {
      routes:
        | '/about/cs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/about/en.vue': {
      routes:
        | '/about/en'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/courses.vue': {
      routes:
        | '/courses'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/guide/index.vue': {
      routes:
        | '/guide/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/guide/cs.vue': {
      routes:
        | '/guide/cs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/guide/en.vue': {
      routes:
        | '/guide/en'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/legal/[locale]/[slug].vue': {
      routes:
        | '/legal/[locale]/[slug]'
      views:
        | never
      pathParamNames:
        | 'slug'
    }
    'src/pages/legal/[slug].vue': {
      routes:
        | '/legal/[slug]'
      views:
        | never
      pathParamNames:
        | 'slug'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
