/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type { ParamValue, ParamValueOneOrMore, ParamValueZeroOrMore, ParamValueZeroOrOne, RouteRecordInfo } from 'vue-router'
import type { _ExtractParamParserType } from 'vue-router/experimental'

declare module 'vue-router' {
	interface TypesConfig {
		_ParamParsers: {}
		RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
		_RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
	}
}

declare module 'vue-router/auto-routes' {
	/**
	 * Route name map generated by vue-router
	 */
	export interface RouteNamedMap {
		'/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>, never>
		'/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>, never>
		'/about/cs': RouteRecordInfo<'/about/cs', '/about/cs', Record<never, never>, Record<never, never>, never>
		'/about/en': RouteRecordInfo<'/about/en', '/about/en', Record<never, never>, Record<never, never>, never>
		'/courses': RouteRecordInfo<'/courses', '/courses', Record<never, never>, Record<never, never>, never>
		'/docs': RouteRecordInfo<
			'/docs',
			'/docs',
			Record<never, never>,
			Record<never, never>,
			| '/docs/cs/faq'
			| '/docs/cs/features/filters'
			| '/docs/cs/features/optimizer'
			| '/docs/cs/features/timetable'
			| '/docs/cs/features/tips-and-tricks'
			| '/docs/cs/getting-started'
			| '/docs/cs/legal/privacy'
			| '/docs/cs/legal/terms'
			| '/docs/cs/mcp'
			| '/docs/en/faq'
			| '/docs/en/features/filters'
			| '/docs/en/features/optimizer'
			| '/docs/en/features/timetable'
			| '/docs/en/features/tips-and-tricks'
			| '/docs/en/getting-started'
			| '/docs/en/legal/privacy'
			| '/docs/en/legal/terms'
			| '/docs/en/mcp'
		>
		'/docs/cs/faq': RouteRecordInfo<'/docs/cs/faq', '/docs/cs/faq', Record<never, never>, Record<never, never>, never>
		'/docs/cs/features/filters': RouteRecordInfo<
			'/docs/cs/features/filters',
			'/docs/cs/features/filters',
			Record<never, never>,
			Record<never, never>,
			never
		>
		'/docs/cs/features/optimizer': RouteRecordInfo<
			'/docs/cs/features/optimizer',
			'/docs/cs/features/optimizer',
			Record<never, never>,
			Record<never, never>,
			never
		>
		'/docs/cs/features/timetable': RouteRecordInfo<
			'/docs/cs/features/timetable',
			'/docs/cs/features/timetable',
			Record<never, never>,
			Record<never, never>,
			never
		>
		'/docs/cs/features/tips-and-tricks': RouteRecordInfo<
			'/docs/cs/features/tips-and-tricks',
			'/docs/cs/features/tips-and-tricks',
			Record<never, never>,
			Record<never, never>,
			never
		>
		'/docs/cs/getting-started': RouteRecordInfo<'/docs/cs/getting-started', '/docs/cs/getting-started', Record<never, never>, Record<never, never>, never>
		'/docs/cs/legal/privacy': RouteRecordInfo<'/docs/cs/legal/privacy', '/docs/cs/legal/privacy', Record<never, never>, Record<never, never>, never>
		'/docs/cs/legal/terms': RouteRecordInfo<'/docs/cs/legal/terms', '/docs/cs/legal/terms', Record<never, never>, Record<never, never>, never>
		'/docs/cs/mcp': RouteRecordInfo<'/docs/cs/mcp', '/docs/cs/mcp', Record<never, never>, Record<never, never>, never>
		'/docs/en/faq': RouteRecordInfo<'/docs/en/faq', '/docs/en/faq', Record<never, never>, Record<never, never>, never>
		'/docs/en/features/filters': RouteRecordInfo<
			'/docs/en/features/filters',
			'/docs/en/features/filters',
			Record<never, never>,
			Record<never, never>,
			never
		>
		'/docs/en/features/optimizer': RouteRecordInfo<
			'/docs/en/features/optimizer',
			'/docs/en/features/optimizer',
			Record<never, never>,
			Record<never, never>,
			never
		>
		'/docs/en/features/timetable': RouteRecordInfo<
			'/docs/en/features/timetable',
			'/docs/en/features/timetable',
			Record<never, never>,
			Record<never, never>,
			never
		>
		'/docs/en/features/tips-and-tricks': RouteRecordInfo<
			'/docs/en/features/tips-and-tricks',
			'/docs/en/features/tips-and-tricks',
			Record<never, never>,
			Record<never, never>,
			never
		>
		'/docs/en/getting-started': RouteRecordInfo<'/docs/en/getting-started', '/docs/en/getting-started', Record<never, never>, Record<never, never>, never>
		'/docs/en/legal/privacy': RouteRecordInfo<'/docs/en/legal/privacy', '/docs/en/legal/privacy', Record<never, never>, Record<never, never>, never>
		'/docs/en/legal/terms': RouteRecordInfo<'/docs/en/legal/terms', '/docs/en/legal/terms', Record<never, never>, Record<never, never>, never>
		'/docs/en/mcp': RouteRecordInfo<'/docs/en/mcp', '/docs/en/mcp', Record<never, never>, Record<never, never>, never>
		'/s/[id]': RouteRecordInfo<'/s/[id]', '/s/:id', { id: ParamValue<true> }, { id: ParamValue<false> }, never>
	}

	/**
	 * Route file to route info map by vue-router.
	 * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
	 *
	 * Each key is a file path relative to the project root with 2 properties:
	 * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
	 * - views: names of nested views (can be passed to <RouterView name="...">)
	 *
	 * @internal
	 */
	export interface _RouteFileInfoMap {
		'src/pages/index.vue': {
			routes: '/'
			views: never
			pathParamNames: never
		}
		'src/pages/about/index.vue': {
			routes: '/about/'
			views: never
			pathParamNames: never
		}
		'src/pages/about/cs.vue': {
			routes: '/about/cs'
			views: never
			pathParamNames: never
		}
		'src/pages/about/en.vue': {
			routes: '/about/en'
			views: never
			pathParamNames: never
		}
		'src/pages/courses.vue': {
			routes: '/courses'
			views: never
			pathParamNames: never
		}
		'src/pages/docs.vue': {
			routes:
				| '/docs'
				| '/docs/cs/faq'
				| '/docs/cs/features/filters'
				| '/docs/cs/features/optimizer'
				| '/docs/cs/features/timetable'
				| '/docs/cs/features/tips-and-tricks'
				| '/docs/cs/getting-started'
				| '/docs/cs/legal/privacy'
				| '/docs/cs/legal/terms'
				| '/docs/cs/mcp'
				| '/docs/en/faq'
				| '/docs/en/features/filters'
				| '/docs/en/features/optimizer'
				| '/docs/en/features/timetable'
				| '/docs/en/features/tips-and-tricks'
				| '/docs/en/getting-started'
				| '/docs/en/legal/privacy'
				| '/docs/en/legal/terms'
				| '/docs/en/mcp'
			views: 'default'
			pathParamNames: never
		}
		'src/pages/docs/cs/faq.md': {
			routes: '/docs/cs/faq'
			views: never
			pathParamNames: never
		}
		'src/pages/docs/cs/features/filters.md': {
			routes: '/docs/cs/features/filters'
			views: never
			pathParamNames: never
		}
		'src/pages/docs/cs/features/optimizer.md': {
			routes: '/docs/cs/features/optimizer'
			views: never
			pathParamNames: never
		}
		'src/pages/docs/cs/features/timetable.md': {
			routes: '/docs/cs/features/timetable'
			views: never
			pathParamNames: never
		}
		'src/pages/docs/cs/features/tips-and-tricks.md': {
			routes: '/docs/cs/features/tips-and-tricks'
			views: never
			pathParamNames: never
		}
		'src/pages/docs/cs/getting-started.md': {
			routes: '/docs/cs/getting-started'
			views: never
			pathParamNames: never
		}
		'src/pages/docs/cs/legal/privacy.md': {
			routes: '/docs/cs/legal/privacy'
			views: never
			pathParamNames: never
		}
		'src/pages/docs/cs/legal/terms.md': {
			routes: '/docs/cs/legal/terms'
			views: never
			pathParamNames: never
		}
		'src/pages/docs/cs/mcp.md': {
			routes: '/docs/cs/mcp'
			views: never
			pathParamNames: never
		}
		'src/pages/docs/en/faq.md': {
			routes: '/docs/en/faq'
			views: never
			pathParamNames: never
		}
		'src/pages/docs/en/features/filters.md': {
			routes: '/docs/en/features/filters'
			views: never
			pathParamNames: never
		}
		'src/pages/docs/en/features/optimizer.md': {
			routes: '/docs/en/features/optimizer'
			views: never
			pathParamNames: never
		}
		'src/pages/docs/en/features/timetable.md': {
			routes: '/docs/en/features/timetable'
			views: never
			pathParamNames: never
		}
		'src/pages/docs/en/features/tips-and-tricks.md': {
			routes: '/docs/en/features/tips-and-tricks'
			views: never
			pathParamNames: never
		}
		'src/pages/docs/en/getting-started.md': {
			routes: '/docs/en/getting-started'
			views: never
			pathParamNames: never
		}
		'src/pages/docs/en/legal/privacy.md': {
			routes: '/docs/en/legal/privacy'
			views: never
			pathParamNames: never
		}
		'src/pages/docs/en/legal/terms.md': {
			routes: '/docs/en/legal/terms'
			views: never
			pathParamNames: never
		}
		'src/pages/docs/en/mcp.md': {
			routes: '/docs/en/mcp'
			views: never
			pathParamNames: never
		}
		'src/pages/s/[id].vue': {
			routes: '/s/[id]'
			views: never
			pathParamNames: 'id'
		}
	}

	/**
	 * Get a union of possible route names in a certain route component file.
	 * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
	 *
	 * @internal
	 */
	export type _RouteNamesForFilePath<FilePath extends string> = _RouteFileInfoMap extends Record<FilePath, infer Info> ? Info['routes'] : keyof RouteNamedMap
}

export {}
