const ScraperInSISCatalogRequestScheduler = 'ScraperInSISCatalogRequestScheduler'
const ScraperInSISStudyPlansRequestScheduler = 'ScraperInSISStudyPlansRequestScheduler'

export { ScraperInSISCatalogRequestScheduler, ScraperInSISStudyPlansRequestScheduler }
