{
 "title": "Crowdsec",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(cs_info, instance)"
    }
   },
   {
    "name": "datasource_type",
    "query": {
     "query": "label_values(cs_parsing_time_seconds_bucket{instance=\"$instance\"}, type)"
    }
   },
   {
    "name": "source",
    "query": {
     "query": "label_values(cs_parsing_time_seconds_bucket{instance=\"$instance\", type=\"$datasource_type\"}, source)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "x": 0, "y": 0, "w": 24, "h": 1 } },
  {
   "title": "Running Crowdsec",
   "type": "stat",
   "gridPos": { "x": 0, "y": 1, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(cs_info)" }
   ]
  },
  {
   "title": "Acquisitions",
   "type": "graph",
   "gridPos": { "x": 6, "y": 1, "w": 18, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cs_filesource_hits_total[$__interval])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(increase(cs_journalctlsource_hits_total[$__interval])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(increase(cs_cloudwatch_stream_hits_total[$__interval])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(increase(cs_syslogsource_hits_total[$__interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "x": 0, "y": 9, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Mem Usage",
     "type": "graph",
     "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Process CPU Usage",
     "type": "graph",
     "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__interval])*100"
      }
     ]
    },
    {
     "title": "Up Since",
     "type": "stat",
     "gridPos": { "x": 16, "y": 0, "w": 4, "h": 4 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(process_start_time_seconds{instance=\"$instance\"})*1000"
      }
     ]
    },
    {
     "title": "Process Open FDs",
     "type": "stat",
     "gridPos": { "x": 20, "y": 0, "w": 4, "h": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_open_fds{instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Process Max FDs",
     "type": "stat",
     "gridPos": { "x": 16, "y": 4, "w": 4, "h": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_max_fds{instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Parsing",
   "type": "row",
   "gridPos": { "x": 0, "y": 10, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Parsers ok",
     "type": "graph",
     "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cs_node_hits_ok_total[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Parsers nok",
     "type": "graph",
     "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cs_node_hits_ko_total[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Parsed lines",
     "type": "graph",
     "gridPos": { "x": 0, "y": 8, "w": 8, "h": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cs_parser_hits_ok_total{instance=\"$instance\"}[$__interval])) by (source)",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Unparsed lines",
     "type": "graph",
     "gridPos": { "x": 8, "y": 8, "w": 8, "h": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cs_parser_hits_ko_total{instance=\"$instance\"}[$__interval])) by (source)",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Parsing time",
     "type": "heatmap",
     "gridPos": { "x": 16, "y": 8, "w": 8, "h": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cs_parsing_time_seconds_bucket{instance=\"$instance\", type=\"$datasource_type\", source=\"$source\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "row",
   "gridPos": { "x": 0, "y": 11, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buckets created",
     "type": "graph",
     "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cs_bucket_created_total[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buckets overflow",
     "type": "graph",
     "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cs_bucket_overflowed_total[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buckets underflow",
     "type": "graph",
     "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cs_bucket_underflowed_total{instance=\"$instance\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buckets Timeline",
     "type": "graph",
     "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(cs_buckets) by (name)", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Bucket pour time",
     "type": "heatmap",
     "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cs_bucket_pour_seconds_bucket{instance=\"$instance\", type=\"$datasource_type\", source=\"$source\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  { "title": "Alerts & Decisions", "type": "row", "gridPos": { "x": 0, "y": 12, "w": 24, "h": 1 } },
  {
   "title": "Decisions Count",
   "type": "stat",
   "gridPos": { "x": 0, "y": 13, "w": 12, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cs_active_decisions)" }
   ]
  },
  {
   "title": "Alerts Count",
   "type": "stat",
   "gridPos": { "x": 12, "y": 13, "w": 12, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cs_alerts)" }
   ]
  },
  {
   "title": "Alerts per Scenario",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 17, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "cs_alerts{instance=\"$instance\"}",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Decisions by scenario",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 25, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "sum(cs_active_decisions) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Decisions By Type",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 34, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(cs_active_decisions) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Totals",
   "type": "row",
   "gridPos": { "x": 0, "y": 42, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Up since",
     "type": "stat",
     "gridPos": { "x": 0, "y": 0, "w": 4, "h": 4 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(process_start_time_seconds{instance=\"$instance\"})*1000",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total raw lines",
     "type": "stat",
     "gridPos": { "x": 4, "y": 0, "w": 5, "h": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(cs_filesource_hits_total{instance=\"$instance\"}[$__interval]) or up * 0) + sum(increase(cs_cloudwatch_stream_hits_total{instance=\"$instance\"}[$__interval]) or up * 0) + sum(increase(cs_journalctlsource_hits_total{instance=\"$instance\"}[$__interval]) or up * 0) + sum(increase(cs_syslogsource_hits_total{instance=\"$instance\"}[$__interval]) or up * 0)"
      }
     ]
    },
    {
     "title": "Total parsed lines",
     "type": "stat",
     "gridPos": { "x": 9, "y": 0, "w": 5, "h": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(cs_parser_hits_ok_total{instance=\"$instance\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Total unparsed lines",
     "type": "stat",
     "gridPos": { "x": 14, "y": 0, "w": 5, "h": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(cs_parser_hits_ko_total{instance=\"$instance\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Total Overflows",
     "type": "stat",
     "gridPos": { "x": 19, "y": 0, "w": 5, "h": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(cs_bucket_overflowed_total{instance=\"$instance\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Top scenarios",
     "type": "bargauge",
     "gridPos": { "x": 0, "y": 4, "w": 24, "h": 8 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(cs_bucket_overflowed_total{instance=\"$instance\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}