export const ASSESSMENT_BUCKETS = [
	{
		key: 'final_test',
		methods: [
			'Absolvování závěrečného testu',
			'Absolvování praktického testu',
			'Absolvování cvičných testů uvažování (CBTs)',
			'Absolvování závěrečné zkoušky - projekty',
			'Absolvování testu (testů)',
			'Týdenní open-book opakovací testy'
		]
	},
	{
		key: 'oral_exam',
		methods: [
			'Absolvování závěrečné ústní zkoušky',
			'Absolvování závěrečné ústní zkoušky – obhajoby případové studie',
			'Diskuse s panelem hodnotitelů',
			'Zpracování právních dokumentů a obhajoba případové studie v rámci závěrečné ústní zkoušky'
		]
	},
	{
		key: 'ongoing_tests',
		methods: [
			'Absolvování průběžného testu (testů)',
			'Absolvování průběžných úkolů',
			'Hodnocené průběžné úkoly',
			'Průběžné kvízy',
			'Domáci práce a průběžné testy',
			'Průběžná aktivita/průběžný test',
			'Průběžná aktivita/průběžné testy',
			'Průběžná práce na projektu a reflexe zpětné vazby',
			'Průběžné domácí úkoly (úpravy kódů, rozšíření modelů, nové datové vstupy, interpretace a prezentace výsledků, …)',
			'Průběžné plnění zadávaných publikačních úkolů',
			'Průběžné plnění zadávaných úkolů',
			'Průběžné úkoly',
			'Příprava zadaných průběžných úkolů',
			'Příprava na bodované aktivity v průběhu semestru (písemné úkoly, videa, prezentace, projekty atd.)',
			'Dílčí úkol / simulace',
			'Dílčí úkoly v průběhu semestru (aktuality, kvízy, videa apod.)',
			'Dílčí úkoly v průběhu semestru (prezentace, skupinová práce, simulace, debaty, videa atd.)',
			'Dílčí úkoly v průběhu semestru (prezentace, texty, kvízy, videa, projekty apod.)',
			'Dílčí úkoly v průběhu semestru (projekty, quízy, videa)',
			'Dílčí úkoly v rámci přípravy na přednášku',
			'Řešení simulačních her a případových studií v průběhu semestru',
			'sady úloh',
			'Testy a dílčí úkoly v průběhu semestru (texty, videa, prezentace, projekty apod.)',
			'Testy a dílčí úkoly v průběhu semestru (texty, videa, prezentace, projekty apod.) Podmínka úspěšného absolvování kurzu - minimálně 60% bodů ze závěrečného elektronického testu (možnost 1 opravy v případě 50-59%).',
			'Testy a dílčí úkoly v průběhu semestru (texty, videa, prezentace, projekty apod.).',
			'Testy a dílčí bodované úkoly v průběhu semestru (texty, videa, prezentace, projekty apod.)',
			'Testy a dílčí úkoly v průběhu semestru (texty, eseje, videa, prezentace, projekty apod.)',
			'Testy a dílčí úkoly v průběhu semestru (texty, prezentace ap.)',
			'Testy a dílčí úkoly v průběhu semestru (texty, videa, skupinové projekty/aktivity apod.)',
			'Výsledek simulační hry',
			'Znalostní kvízy',
			'Publikační body dle hodnoticích kritérií fakulty'
		]
	},
	{
		key: 'paper_project',
		methods: [
			'Vypracování semestrální práce',
			'Vypracování domácích úkolů',
			'Vypracování domácích úloh',
			'Vypracování domácího úkolu',
			'Vypracování průběžných domácích úkolů',
			'Vypracování průběžných úkolů',
			'Vypracování projektu',
			'vypracování projektu',
			'Vypracování individuálních úkolů',
			'Vypracování týmového úkolu',
			'Vypracování analýzy',
			'Vypracování a obhajoba eseje',
			'Vypracování posudku (posudků).',
			'Vypracování podkladů dotazníkového šetření',
			'Vypracování osobního plánu rozvoje (20 %), průběžná reflexe práce v týmu (20 %)',
			'Vypracování osobních ponaučení (3 %). Účast na projektu osobního rozvoje (8 %).',
			'Vypracování písemných úkolů',
			'Vypracování podcastu',
			'Vypracování pracovních listů',
			'Vypracování případových studií',
			'Vypracování recenze vybrané publikace',
			'Vypracování simulace',
			'Vypracování základu diplomové práce',
			'Vypracování zprávy z výzkumného pobytu',
			'Vypracování expertního stanoviska',
			'Vypracování hodnocení projektu jiné skupiny',
			'Vypracování individuální práce',
			'Vypracování komplexního projektu',
			'Vypracování projektu bakalářské práce a jeho prezentace',
			'Vypracování projektu semestrální práce',
			'vypracování krátkých případových studií',
			'vypracování dopisů',
			'vypracování a obhajoba týmového projektu',
			'Zpracování inovačního projektu',
			'Zpracování Learning Journalů.',
			'Zpracování metodologie diplomové práce',
			'Zpracování průběžných úkolů',
			'Zpracování a obhajoba případové studie',
			'Zpracování a obhajoba rešerše literatury',
			'Zpracování a obhajoba zadané case study',
			'Zpracování dílčích úkolů v rámci přípravy na semináře a zpracování úkolů během seminářů.',
			'Zpracování dotazníkového šetření',
			'Zpracování eseje.',
			'Zpracování právních dokumentů a obhajoba případové studie',
			'Zpracování samostatných prací',
			'Zpracování studentského projektu',
			'Zpracování úkolů v Moodlu',
			'Práce na studentském projektu',
			'Případová studie',
			'Případové studie',
			'Osobní případová studie',
			'Rešerše odborné literatury',
			'Řešení případové studie',
			'Řešení případových studií',
			'Řešení úkolů v rámci výuky a domácích úkolů, popř. projektu',
			'Esej',
			'Závěrečná esej na vybrané téma studentem',
			'Závěrečná práce - projekt',
			'Závěrečná případová studie (50), Absolvování tradingového experimentu (15)',
			'Individuální písemné práce - kreativizace osobnosti, výlet z konformní zóny, závěrečná odborná esej',
			'Individuální práce a řešení dílčích případových studií',
			'Individuální rozvojový plán',
			'Individuální úkol',
			'Individuelní sebereflexe, zápisy z jednání apod.',
			'Indiviudální úkoly',
			'Inovační projekt (prezentace 20%, zpráva 30%, vzájemné hodnocení 10%)',
			'Jiný požadavek: Příprava na řešení příkladů z praxe - shrnutí celé látky',
			'Písemné sebereflexe',
			'Písemné shrnutí povinné četby před začátkem kurzu',
			'Písemná práce na základě materiálů v rámci cvičení',
			'Písemná příprava na semináře',
			'Osobní učební plán (individuální plán rozvoje dovedností; sebereflexe a sebehodnocení).',
			'Analýza a zajištění datové dostupnosti vybraného ukazatele',
			'Analýza reálných datových souborů',
			'Domácí úkoly.',
			'Domácí úkoly, průběžné testy, další semestrální práce - konkrétní požadavky závisí na cvičícím a oznámí je studentům první týden výuky',
			'Domácí příprava a Moodle',
			'Domácí příprava a její hodnocení',
			'Domácí příprava a úkoly v Moodlu',
			'domácí úkoly',
			'domácí úkoly v Moodle',
			'Domácí práce',
			'Domácí zadání',
			'Hodnocené úkoly v LMS',
			'Hodnocené aktivity v Moodlu, Business role-play, Report writing',
			'Hodnocené aktivity v Moodle',
			'aktivity v moodlu',
			'Týmové řešení vybraného problému',
			'Týmové semestrální projekty',
			'Týmový semestrální projekt',
			'Tvorba datově analytického řešení a jeho obhajoba',
			'Praktická konstrukce investičního doporučení',
			'Odevzdání podkladů pro praktický úkol - CV, motivační dopis 30%, splnění praktického úkolu - modelový přijímací pohovor 30%',
			'Koreferát',
			'Komentář',
			'Kvalita semestrální práce',
			'Kvalitativní šetření',
			'Learning Journal',
			'Microethnography submissions (#1 and #2)',
			'Oponentský posudek',
			'Pedagogický deník z průběžné pedagogické praxe',
			'Popis individuálního přínosu pro týmový projekt',
			'Portfolio sestávající z: a) Sestavení korpusu o rozsahu 30 000 slov na vlastní zvolené téma související s mezinárodními vztahy (např. diplomatický diskurz, mediální prezentace mezinárodních témat). b) Shrnutí (500–1 000 slov) představující klíčové závěry, vizualizace a interpretace ve formátu vhodném pro akademickou nebo profesionální komunikaci.',
			'Portfolio sestávající z a) sestavení korpusu o rozsahu 50 000 slov na zvolené téma (např. zprávy o zveřejňování informací společností, diplomatické projevy, online recenze) a b) shrnutí (500–1 000 slov) představující klíčové závěry, vizualizace a interpretace pro akademické nebo odborné publikum.',
			'Pracovní listy',
			'Práce na hodinách, domácí úkoly',
			'Profesní portfólio z pedagogické praxe',
			'Projekt zadání diplomové práce včetně rešerše',
			'Projektové dokumenty',
			'Projektové synopse – úvodní (3 str., 12pt, 2 týdny před seminářem) a upravená verze po semináři.',
			'Příprava domácích úkolů',
			'Příprava na cvičení',
			'Příprava semestrálního projektu',
			'Recenze projektů ostatních studentů',
			'Reflexe',
			'Reflexe na přečtenou knihu',
			'Reflexe týmové práce',
			'Regulatorní diskuzní příspěvky v Moodle a individuální úkol spojený s regulací/financemi',
			'Schválené zadání diplomové práce (15%), Harmonogram práce (5%), Prezentace a oponentura rozpracovaných částí DP (20%)',
			'Sebereflexe (individuální písemná práce)',
			'Seminární práce',
			'Semestrální práce a její prezentace',
			'Terénní zápisky',
			'Úkoly zpracovávané na cvičeních a v rámci domácí přípravy na výuku',
			'14 denní časový snímek',
			'Cíle a téma DP',
			'Data-based critical thinking project',
			'Dílčí výsledky DP',
			'Writing a Proposal',
			'Osobní přínos projektu'
		]
	},
	{
		key: 'presentation',
		methods: [
			'Prezentace nebo obhajoba',
			'Prezentace úloh',
			'ústní prezentace',
			'Obhajoba projektu',
			'aktivní účast na přednášce (krátká prezentace)',
			'Projev na vybrané téma',
			'Recenze',
			'Případová studie - prezentace výsledků před komisí',
			'Prezentace semestrální práce na workshopu',
			'Obhajoba týmového projektu',
			'Obhajoba semestrálního projektu',
			'Obhajoba semestrální práce',
			'Obhajoba projektu stáže',
			'Obhajoba individuálního kariérního plánu',
			'obhajoba závěrečné práce',
			'Prezentace závěrečné práce na workshopu',
			'Úvodní prezentace/esey',
			'Krátká prezentace projektu',
			'Prezentace návrhu řešení',
			'Prezentace vlastního výzkumného projektu a obhajoba jeho metodologické části'
		]
	},
	{
		key: 'activity',
		methods: [
			'Aktivita na přednáškách/cvičeních/seminářích',
			'Aktivita na praxi (hodnocení zodpovědných osob)',
			'Aktivita na seminářích',
			'Aktivita v Moodlu',
			'Aktivity před začátkem kursu',
			'Aktivity před začátkem kursu (řízená četba)',
			'Aktivity před začátkem kurzu – absolvování vybraných modulů z Digitální garáže Google',
			'Aktivity před začátkem kurzu – řízená četba a její ověření',
			'aktivity v moodlu',
			'Aktivní práce na cvičeních, hodnocení simulačních her a případových studií',
			'certifikace „Digitální garáž"',
			'Čtení textu nahlas',
			'Diskuse',
			'Docházka',
			'exkurze',
			'Facilitace workshopů o technikách inovací',
			'Hodnocení ostatních členů týmu',
			'Hodnocení prezentace jiného týmu',
			'Internship',
			'Kritické hodnocení ostatních projektů',
			'Kritické hodnocení prezentace jiného týmu',
			'Min. účast na hodinách 80%',
			'Moodle',
			'Peer evaluation (Group based)',
			'peer review',
			'povinná účast na cvičeních (vyučující může tolerovat max. 3 omluvené absence)',
			'Pracovní schůze a aktivity procvičující mluvní dovednosti',
			'Právní hra',
			'Praxe + zpracování projektu diplomové práce',
			'Praxe, exkurze nebo praktický projekt',
			'predikční hra',
			'Predikční hra',
			'překlad z češtiny do angličtiny, atd',
			'Průběžná analýza přednášek',
			'Skupinová práce',
			'Stáž ve státní správě',
			'Student je povinen se účastnit cvičení. Aktivita ve formě testů v LMS (Aktivita bude posuzována na základě průměrné úspěšnosti ze čtyř testů, přičemž za 100% úspěšnost z každého testu získá student/ka 20 bodů.',
			'účast a aktivita na odborné exkurzi',
			'Účast na celosemestrálním projektu',
			'účast na cvičeních',
			'Účast na exkurzi',
			'účast na odborné exkurzi',
			'Účast na přednáškách',
			'Účast na přednáškách/cvičeních minimálně 80 %',
			'účast na tematické exkurzi',
			'účast v právní hře nebo vypracování semestrální práce',
			'Výkon odborné praxe',
			'Výkon praxe',
			'Výkon praxe (90 %), Vypracovaní zprávy a rozprava o praxi (10 %)',
			'Vzájemné hodnocení (peer assessment)',
			'Zvláštní podmínky a podrobnosti'
		]
	}
] as const

export type AssessmentBucketKey = (typeof ASSESSMENT_BUCKETS)[number]['key']
