export const ASSESSMENT_BUCKETS = [
	{
		key: 'final_test',
		methods: [
			'Absolvování závěrečného testu',
			'Absolvování praktického testu',
			'Absolvování cvičných testů uvažování (CBTs)',
			'Absolvování závěrečné zkoušky - projekty',
		],
	},
	{
		key: 'oral_exam',
		methods: [
			'Absolvování závěrečné ústní zkoušky',
			'Absolvování závěrečné ústní zkoušky – obhajoby případové studie',
			'Diskuse s panelem hodnotitelů',
		],
	},
	{
		key: 'ongoing_tests',
		methods: [
			'Absolvování průběžného testu (testů)',
			'Absolvování průběžných úkolů',
			'Hodnocené průběžné úkoly',
			'Průběžné kvízy',
			'Domáci práce a průběžné testy',
			'Testy a dílčí úkoly v průběhu semestru (texty, videa, prezentace, projekty apod.)',
			'Testy a dílčí úkoly v průběhu semestru (texty, videa, prezentace, projekty apod.).',
			'Testy a dílčí bodované úkoly v průběhu semestru (texty, videa, prezentace, projekty apod.)',
			'Testy a dílčí úkoly v průběhu semestru (texty, eseje, videa, prezentace, projekty apod.)',
			'Testy a dílčí úkoly v průběhu semestru (texty, prezentace ap.)',
			'Testy a dílčí úkoly v průběhu semestru (texty, videa, prezentace, projekty apod.) Podmínka úspěšného absolvování kurzu - minimálně 60% bodů ze závěrečného elektronického testu (možnost 1 opravy v případě 50-59%).',
			'Příprava na bodované aktivity v průběhu semestru (písemné úkoly, videa, prezentace, projekty atd.)',
			'Dílčí úkoly v průběhu semestru (projekty, quízy, videa)',
		],
	},
	{
		key: 'paper_project',
		methods: [
			'Vypracování semestrální práce',
			'Vypracování domácích úkolů',
			'Vypracování domácího úkolu',
			'Vypracování průběžných domácích úkolů',
			'Vypracování projektu',
			'Vypracování individuálních úkolů',
			'Vypracování týmového úkolu',
			'Vypracování analýzy',
			'Vypracování a obhajoba eseje',
			'Vypracování posudku (posudků).',
			'Vypracování podkladů dotazníkového šetření',
			'Vypracování osobního plánu rozvoje (20 %), průběžná reflexe práce v týmu (20 %)',
			'Vypracování osobních ponaučení (3 %). Účast na projektu osobního rozvoje (8 %).',
			'vypracování krátkých případových studií',
			'vypracování dopisů',
			'Vypracování domácích úloh',
			'vypracování a obhajoba týmového projektu',
			'Zpracování inovačního projektu',
			'Zpracování Learning Journalů.',
			'Zpracování metodologie diplomové práce',
			'Zpracování průběžných úkolů',
			'Práce na studentském projektu',
			'Případová studie',
			'Případové studie',
			'Osobní případová studie',
			'Řešení případové studie',
			'Rešerše odborné literatury',
			'Esej',
			'Závěrečná esej na vybrané téma studentem',
			'Individuální písemné práce - kreativizace osobnosti, výlet z konformní zóny, závěrečná odborná esej',
			'Písemné sebereflexe',
			'Písemné shrnutí povinné četby před začátkem kurzu',
			'Osobní učební plán (individuální plán rozvoje dovedností; sebereflexe a sebehodnocení).',
			'Analýza a zajištění datové dostupnosti vybraného ukazatele',
			'Domácí úkoly.',
			'Domácí úkoly, průběžné testy, další semestrální práce - konkrétní požadavky závisí na cvičícím a oznámí je studentům první týden výuky',
			'Domácí příprava a Moodle',
			'domácí úkoly',
			'Hodnocené úkoly v LMS',
			'aktivity v moodlu',
			'Hodnocené aktivity v Moodlu, Business role-play, Report writing',
			'Hodnocené aktivity v Moodle',
			'Týmové řešení vybraného problému',
			'Praktická konstrukce investičního doporučení',
			'Odevzdání podkladů pro praktický úkol - CV, motivační dopis 30%, splnění praktického úkolu - modelový přijímací pohovor 30%',
			'Koreferát',
			'Indiviudální úkoly',
			'Portfolio sestávající z: a) Sestavení korpusu o rozsahu 30 000 slov na vlastní zvolené téma související s mezinárodními vztahy (např. diplomatický diskurz, mediální prezentace mezinárodních témat). b) Shrnutí (500–1 000 slov) představující klíčové závěry, vizualizace a interpretace ve formátu vhodném pro akademickou nebo profesionální komunikaci.',
		],
	},
	{
		key: 'presentation',
		methods: [
			'Prezentace nebo obhajoba',
			'Prezentace úloh',
			'ústní prezentace',
			'Obhajoba projektu',
			'aktivní účast na přednášce (krátká prezentace)',
			'Projev na vybrané téma',
			'Recenze',
		],
	},
	{
		key: 'activity',
		methods: [
			'Aktivita na přednáškách/cvičeních/seminářích',
			'Skupinová práce',
			'Účast na přednáškách',
			'účast a aktivita na odborné exkurzi',
			'účast na cvičeních',
			'Účast na celosemestrálním projektu',
			'účast na odborné exkurzi',
			'účast na tematické exkurzi',
			'Praxe, exkurze nebo praktický projekt',
			'Stáž ve státní správě',
			'exkurze',
			'predikční hra',
			'překlad z češtiny do angličtiny, atd',
			'Čtení textu nahlas',
			'certifikace „Digitální garáž"',
			'Aktivity před začátkem kurzu – absolvování vybraných modulů z Digitální garáže Google',
			'Aktivity před začátkem kursu',
			'Zvláštní podmínky a podrobnosti',
			'účast v právní hře nebo vypracování semestrální práce',
			'Průběžná analýza přednášek',
			'Práce na hodinách, domácí úkoly',
			'Student je povinen se účastnit cvičení. Aktivita ve formě testů v LMS (Aktivita bude posuzována na základě průměrné úspěšnosti ze čtyř testů, přičemž za 100% úspěšnost z každého testu získá student/ka 20 bodů.',
		],
	},
] as const

export type AssessmentBucketKey = (typeof ASSESSMENT_BUCKETS)[number]['key']
