export {
	FacultyTable,
	CourseTable,
	CourseAssessmentTable,
	CourseUnitTable,
	CourseUnitSlotTable,
	StudyPlanTable,
	StudyPlanCourseTable,
	StudyPlanCourseIdentTable,
	AcademicPeriodTable,
	AcademicScheduleEventTable
} from './types'

export type {
	Database,
	ExcludeMethods,
	Faculty,
	NewFaculty,
	FacultyWithRelations,
	Course,
	NewCourse,
	CourseWithRelations,
	CourseAssessment,
	NewCourseAssessment,
	CourseAssessmentWithRelations,
	CourseUnit,
	NewCourseUnit,
	CourseUnitWithRelations,
	CourseUnitSlot,
	NewCourseUnitSlot,
	CourseUnitSlotWithRelations,
	StudyPlan,
	NewStudyPlan,
	StudyPlanWithRelations,
	StudyPlanCourse,
	NewStudyPlanCourse,
	StudyPlanCourseWithRelations,
	StudyPlanCourseIdent,
	NewStudyPlanCourseIdent,
	AcademicPeriod,
	NewAcademicPeriod,
	AcademicScheduleEvent,
	NewAcademicScheduleEvent
} from './types'
