name: Deploy Monitoring
'on':
    workflow_dispatch: null
permissions:
    contents: read
    packages: read
concurrency:
    group: deploy-monitoring
    cancel-in-progress: false
jobs:
    deploy:
        if: github.ref == 'refs/heads/main'
        uses: ./.github/workflows/_deploy-service.yml
        with:
            environment: monitoring
            source_commit: ${{ github.sha }}
        secrets: inherit
