# ==============================================================================
# Networks Configuration: Traefik
# Description: Global network definitions for Traefik reverse proxy.
# ==============================================================================

networks:
  public-network:
    name: public-network
    external: true
    driver: bridge

  alloy-network:
    name: alloy-network
    external: true
